
const cardData = [
  {
    title: 'React Basics',
    text: 'Learn the fundamentals of React, a popular JavaScript library for building user interfaces.',
    image: 'https://img.freepik.com/free-photo/abstract-pastel-background-with-gradient-effect-generated-by-ai_188544-9886.jpg',
    listItems: ['JSX', 'Components', 'State Management'],
    links: ['React Documentation', 'React Tutorial'],
    courses: ['React'],
    info: 'Start your journey with React and understand the core concepts.',
  },
  {
    title: 'Advanced React',
    text: 'Dive deeper into React with hooks, context API, and advanced patterns.',
    image: 'https://img.freepik.com/free-photo/colorful-abstract-background-with-oil-painting-technique-generated-by-ai_188544-9873.jpg',
    listItems: ['Hooks', 'Context API', 'Higher-Order Components'],
    links: ['Advanced React Guide', 'React Patterns'],
    courses: ['React', 'React Hooks'],
    info: 'Master advanced React concepts for building complex applications.',
  },
  {
    title: 'Node.js Essentials',
    text: 'Understand the basics of Node.js for server-side programming.',
    image: 'https://img.freepik.com/free-photo/abstract-pastel-background-with-mesh-effect-generated-by-ai_188544-9885.jpg',
    listItems: ['Event Loop', 'Express.js', 'APIs'],
    links: ['Node.js Documentation', 'Express Guide'],
    courses: ['Node.js', 'Express.js'],
    info: 'Build scalable network applications using Node.js and Express.',
  },
  {
    title: 'Full-Stack JavaScript',
    text: 'Learn to build full-stack applications using JavaScript, from front-end to back-end.',
    image: 'https://img.freepik.com/free-photo/abstract-pastel-background-with-gradient-effect-generated-by-ai_188544-9886.jpg',
    listItems: ['React', 'Node.js', 'MongoDB'],
    links: ['MERN Stack', 'Full-Stack Course'],
    courses: ['MERN Stack', 'Full-Stack JavaScript'],
    info: 'Become a full-stack developer with the MERN stack.',
  },
  {
    title: 'Python for Data Science',
    text: 'Explore data science techniques using Python libraries like Pandas and NumPy.',
    image: 'https://img.freepik.com/free-photo/abstract-gradient-pink-purple-background-generated-by-ai_188544-9901.jpg',
    listItems: ['Pandas', 'NumPy', 'Matplotlib'],
    links: ['Pandas Documentation', 'NumPy Guide'],
    courses: ['Python', 'Data Science'],
    info: 'Analyze and visualize data with Python for Data Science.',
  },
  {
    title: 'Machine Learning with Python',
    text: 'Learn how to implement machine learning algorithms using Python.',
    image: 'https://img.freepik.com/free-photo/colorful-abstract-background-with-fluid-pattern-generated-by-ai_188544-9878.jpg',
    listItems: ['Supervised Learning', 'Unsupervised Learning', 'Scikit-learn'],
    links: ['Machine Learning Guide', 'Scikit-learn Documentation'],
    courses: ['Machine Learning', 'Python'],
    info: 'Develop predictive models using Python for machine learning.',
  },
  {
    title: 'Angular for Beginners',
    text: 'Get started with Angular and build dynamic web applications.',
    image: 'https://img.freepik.com/free-photo/abstract-pastel-background-with-fluid-pattern-generated-by-ai_188544-9882.jpg',
    listItems: ['Components', 'Directives', 'Services'],
    links: ['Angular Documentation', 'Angular Tutorial'],
    courses: ['Angular'],
    info: 'Build powerful and efficient web apps with Angular.',
  },
  {
    title: 'Vue.js Fundamentals',
    text: 'Learn the core concepts of Vue.js and build interactive web applications.',
    image: 'https://img.freepik.com/free-photo/abstract-pastel-background-with-gradient-pattern-generated-by-ai_188544-9880.jpg',
    listItems: ['Directives', 'Vue Router', 'Vuex'],
    links: ['Vue.js Guide', 'Vue.js Best Practices'],
    courses: ['Vue.js'],
    info: 'Create interactive user interfaces with Vue.js.',
  },
  {
    title: 'TypeScript Essentials',
    text: 'Master TypeScript to write robust and maintainable JavaScript code.',
    image: 'https://img.freepik.com/free-photo/colorful-abstract-background-with-fluid-painting-generated-by-ai_188544-9877.jpg',
    listItems: ['Type Annotations', 'Interfaces', 'Generics'],
    links: ['TypeScript Handbook', 'TypeScript Tutorial'],
    courses: ['TypeScript'],
    info: 'Enhance your JavaScript projects with TypeScript.',
  },
  {
    title: 'Database Management with SQL',
    text: 'Learn SQL to manage and manipulate relational databases efficiently.',
    image: 'https://img.freepik.com/free-photo/abstract-pastel-background-with-oil-painting-pattern-generated-by-ai_188544-9874.jpg',
    listItems: ['Joins', 'Subqueries', 'Transactions'],
    links: ['SQL Tutorial', 'Database Design'],
    courses: ['SQL', 'Database Management'],
    info: 'Manage and query databases effectively with SQL.',
  },
  {
    title: 'Docker for Developers',
    text: 'Understand the basics of Docker and how to containerize applications.',
    image: 'https://img.freepik.com/free-photo/abstract-gradient-pink-purple-background-generated-by-ai_188544-9901.jpg',
    listItems: ['Containers', 'Docker Compose', 'Docker Hub'],
    links: ['Docker Documentation', 'Docker Compose Guide'],
    courses: ['Docker'],
    info: 'Deploy and manage applications with Docker containers.',
  },
  {
    title: 'DevOps with CI/CD',
    text: 'Learn continuous integration and continuous deployment practices using DevOps tools.',
    image: 'https://img.freepik.com/free-photo/colorful-abstract-background-with-fluid-painting-effect-generated-by-ai_188544-9879.jpg',
    listItems: ['Jenkins', 'CI/CD Pipelines', 'Automation'],
    links: ['Jenkins Documentation', 'CI/CD Best Pract'],
    courses: ['DevOps', 'CI/CD'],
    info: 'Streamline development processes with CI/CD and DevOps practices.',
  },
  ];
  
  export default cardData;