
const cardData = [
  {
    title: 'React Basics',
    text: 'Learn the fundamentals of React, a popular JavaScript library for building user interfaces.',
    image: 'https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/5992673/cover_image/retina_1708x683/1005_Design-Patterns-in-React_Cover-44247834a5b31e8d08e5bbbdac4a6750.png',
    listItems: ['JSX', 'Components', 'State Management'],
    links: ['React Documentation', 'React Tutorial'],
    courses: ['React'],
    info: 'Start your journey with React and understand the core concepts.',
  },
  {
    title: 'Advanced React',
    text: 'Dive deeper into React with hooks, context API, and advanced patterns.',
    image: 'https://www.patterns.dev/img/reactjs/react-logo@3x.svg',
    listItems: ['Hooks', 'Context API', 'Higher-Order Components'],
    links: ['Advanced React Guide', 'React Patterns'],
    courses: ['React', 'React Hooks'],
    info: 'Master advanced React concepts for building complex applications.',
  },
  {
    title: 'Node.js Essentials',
    text: 'Understand the basics of Node.js for server-side programming.',
    image: 'https://cdn.pixabay.com/photo/2015/04/23/17/41/node-js-736399_960_720.png',
    listItems: ['Event Loop', 'Express.js', 'APIs'],
    links: ['Node.js Documentation', 'Express Guide'],
    courses: ['Node.js', 'Express.js'],
    info: 'Build scalable network applications using Node.js and Express.',
  },
  {
    title: 'Full-Stack JavaScript',
    text: 'Learn to build full-stack applications using JavaScript, from front-end to back-end.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFX9mNYv1We2nYQ2SD4cHsxBrEouMGxmwE8Q&s',
    listItems: ['React', 'Node.js', 'MongoDB'],
    links: ['MERN Stack', 'Full-Stack Course'],
    courses: ['MERN Stack', 'Full-Stack JavaScript'],
    info: 'Become a full-stack developer with the MERN stack.',
  },
  {
    title: 'Python for Data Science',
    text: 'Explore data science techniques using Python libraries like Pandas and NumPy.',
    image: 'https://img-c.udemycdn.com/course/750x422/919038_3ae1_13.jpg',
    listItems: ['Pandas', 'NumPy', 'Matplotlib'],
    links: ['Pandas Documentation', 'NumPy Guide'],
    courses: ['Python', 'Data Science'],
    info: 'Analyze and visualize data with Python for Data Science.',
  },
  {
    title: 'Machine Learning with Python',
    text: 'Learn how to implement machine learning algorithms using Python.',
    image: 'https://cdn.pixabay.com/photo/2024/01/29/22/47/ai-generated-8540915_960_720.jpg',
    listItems: ['Supervised Learning', 'Unsupervised Learning', 'Scikit-learn'],
    links: ['Machine Learning Guide', 'Scikit-learn Documentation'],
    courses: ['Machine Learning', 'Python'],
    info: 'Develop predictive models using Python for machine learning.',
  },
  {
    title: 'Angular for Beginners',
    text: 'Get started with Angular and build dynamic web applications.',
    image: 'https://www.openlogic.com/sites/default/files/image/2023-01/image-blog-openlogic-what-is-angularjs-1.png',
    listItems: ['Components', 'Directives', 'Services'],
    links: ['Angular Documentation', 'Angular Tutorial'],
    courses: ['Angular'],
    info: 'Build powerful and efficient web apps with Angular.',
  },
  {
    title: 'Vue.js Fundamentals',
    text: 'Learn the core concepts of Vue.js and build interactive web applications.',
    image: 'https://api.otakoyi.software/uploads/content/2023/11/20/1280/vuejs-and-seo--your-steps-to-take-to-become-more-seo-friendly-317x237.webp',
    listItems: ['Directives', 'Vue Router', 'Vuex'],
    links: ['Vue.js Guide', 'Vue.js Best Practices'],
    courses: ['Vue.js'],
    info: 'Create interactive user interfaces with Vue.js.',
  },
  {
    title: 'TypeScript Essentials',
    text: 'Master TypeScript to write robust and maintainable JavaScript code.',
    image: 'https://www.orientsoftware.com/Themes/Content/Images/blog/2023-11-13/typescript-introduction.jpg',
    listItems: ['Type Annotations', 'Interfaces', 'Generics'],
    links: ['TypeScript Handbook', 'TypeScript Tutorial'],
    courses: ['TypeScript'],
    info: 'Enhance your JavaScript projects with TypeScript.',
  },
  {
    title: 'Database Management with SQL',
    text: 'Learn SQL to manage and manipulate relational databases efficiently.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-8f_zPxdTAO0x2VC8o47eRCdMhGmn0IDnBA&s',
    listItems: ['Joins', 'Subqueries', 'Transactions'],
    links: ['SQL Tutorial', 'Database Design'],
    courses: ['SQL', 'Database Management'],
    info: 'Manage and query databases effectively with SQL.',
  },
  {
    title: 'Docker for Developers',
    text: 'Understand the basics of Docker and how to containerize applications.',
    image: 'https://static1.howtogeekimages.com/wordpress/wp-content/uploads/csit/2021/04/075c8694.jpeg',
    listItems: ['Containers', 'Docker Compose', 'Docker Hub'],
    links: ['Docker Documentation', 'Docker Compose Guide'],
    courses: ['Docker'],
    info: 'Deploy and manage applications with Docker containers.',
  },
  {
    title: 'DevOps with CI/CD',
    text: 'Learn continuous integration and continuous deployment practices using DevOps tools.',
    image: 'https://media.istockphoto.com/id/1489620329/photo/hand-of-human-putting-hexagon-piece-to-full-fill-the-part-of-software-development-and-it.webp?s=2048x2048&w=is&k=20&c=sip3reNENIXj23OURx_oJdAVxthyLGvzTm0pr553fM4=',
    listItems: ['Jenkins', 'CI/CD Pipelines', 'Automation'],
    links: ['Jenkins Documentation', 'CI/CD Best Pract'],
    courses: ['DevOps', 'CI/CD'],
    info: 'Streamline development processes with CI/CD and DevOps practices.',
  },
  ];
  
  export default cardData;